In [7]:
import numpy as np

a1 = np.array([1,2,3,4,5])
print(a1) # numpy 배열은 ','가 없이 생성

[1 2 3 4 5]


In [10]:
a2 = np.array([[1,2,3],[4,5,6]]) #2차원 배열
print(a2)

[[1 2 3]
 [4 5 6]]


In [13]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3차원 배열
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# 배열 메서드
print(a2.shape)
print(a2.ndim)
print(a2.dtype)
print(a2.itemsize)
print(a2.size)

(2, 3)
2
int64
8
6


In [29]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) #2차원 배열(3*3) 생성
print(arr[0,1])
rows = [0,2]
cols = [2,2]
print(arr[rows,cols])

2
[3 9]


In [34]:
arr = np.array([10,20,30,40,50])
print(arr[arr>20])
print(arr[arr%20==0])
arr[arr>20] = 0
print(arr)
lists = [1, 2]
print(arr[lists])

[30 40 50]
[20 40]
[10 20  0  0  0]
[20  0]


In [43]:
# 여러가지 형태의 배열 생성
zero = np.zeros((3,3))
print(zero)

one = np.ones((3,3))
print(one)

arange = np.arange(1,20,3) #간격이 명확할 때 사용
print(arange)

linspace = np.linspace(0,8,10) #일정한 간격의 value가 필요한 때
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 1  4  7 10 13 16 19]
[0.         0.88888889 1.77777778 2.66666667 3.55555556 4.44444444
 5.33333333 6.22222222 7.11111111 8.        ]


In [48]:
arr = np.array([1,2,3,4,5,6,7,8,9])

reshaped = np.reshape(arr,(3,3))
print(reshaped)

resized = np.resize(arr,(4,4))
print(resized)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [4 5 6 7]]


In [66]:
# np를 이용한 배열 사칙연산
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

a2 = np.array([1,4,9,16,25,36])
print(np.sqrt(a2))
print(np.exp(a2))
print(np.log(a2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]
[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]


In [69]:
angles = np.array([0, np.pi/6,np.pi/4,np.pi/3,np.pi/2])
print(np.sin(angles))
print(np.cos(angles))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [77]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.hstack((a,b)))
print(np.vstack((a,b)))
print(np.column_stack((a,b)))

a = np.array([[1,2,3],[4,5,6]])
print(np.hsplit(a,3))
print(np.vsplit(a,2))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [79]:
a = np.array([1,2,3,4,5])
num = 10
print(num + a)

a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])

print(a+b)

[11 12 13 14 15]
[[11 22 33]
 [14 25 36]]
